### ISSUE TITLE
parse_qs is not defined

### ISSUE THREAD

**Issue by arshavin69ru** [yausername/youtubedl-android#104]
I am using the library in an android app, it was working until 3 days ago, and suddenly it has completely broken down. I believe this a python module, but why is it missing? Here is the detail about the error.

com.yausername.youtubedl_android.YoutubeDLException: Traceback (most recent call last):
  File "/data/user/0/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/data/data/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/data/data/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/data/data/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "/data/data/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 791, in extract_info
    if not ie.suitable(url):
  File "/data/data/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 2085, in suitable
    return False if YoutubeIE.suitable(url) else super(
  File "/data/data/com.android.learn.jetpack_playground/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 5612, in suitable
    qs = parse_qs(url)
NameError: name 'parse_qs' is not defined

**Comment by xibr** [comment]
This has been fixed. You must remove app data and try again.

**Comment by arshavin69ru** [comment]
> 
> 
> This has been fixed. You must remove app data and try again.

I am still getting the same error. In my application, The first thing I do, is initialize youtube-dl and check for any updates when the app starts. Initialization and updates have no issue, but when I start extracting media from any youtube link, it throws this error. However, some twitter and insta links work normally. But youtube doesn't work at all. I just checked by removing app data, nothing changed.

**Comment by arshavin69ru** [comment]
> 
> 
> Have you removed application data? If yes, everything should work fine.

I actually used the other solution from another post on your page, I used the modified youtuble-dl.zip and rebuilt my app, it seems to work now, but I need to make sure that the library has been updated with the fix, I will make sure and close this issue.

**Comment by xibr** [comment]
OK, See [https://github.com/yausername/youtubedl-lazy/issues/7](https://github.com/yausername/youtubedl-lazy/issues/7)
 
You can use youtube_dl.zip here [https://github.com/yausername/youtubedl-lazy/releases/tag/2021.04.17](https://github.com/yausername/youtubedl-lazy/releases/tag/2021.04.17) to make sure the issue is resolved.

**Comment by arshavin69ru** [comment]
> 
> 
> OK, See [yausername/youtubedl-lazy#7](https://github.com/yausername/youtubedl-lazy/issues/7)
> 
> You can use youtube_dl.zip here https://github.com/yausername/youtubedl-lazy/releases/tag/2021.04.17 to make sure the issue is resolved.

Thanks! I am already using this and it works. But, if I update it from my app, will it break again?

**Comment by xibr** [comment]
>  if I update it from my app, will it break again? 

No, it should be working properly.
