### ISSUE TITLE
Suddenly library stopped working

### ISSUE THREAD

**Issue by HaXxanParhar** [yausername/youtubedl-android#162]
I added this dependency to my Android project
`
    // Youtube.dl library
    implementation 'com.github.yausername.youtubedl-android:library:-SNAPSHOT'`

It was working a couple of hours earlier but now this is not working. Is the dependency removed from the server? If yes, when will it be restored? If not, Is there any alternative? 

The following dependency (present in the docs) was not working for me so I was told to use the above-mentioned dependency. And now it is also not working. 
`implementation 'com.github.yausername.youtubedl-android:library:0.13.1'`

I'm working on an app and because of this, I can't do anything now. Kindly resolve this issue. Thanks

**Comment by Aakash330** [comment]
same issue i am facing ..

**Comment by SuperSonicHub1** [comment]
Same here.

**Comment by SuperSonicHub1** [comment]
I think the issue we're having is with JitPack and not with the maintainers, so I made an issue: https://github.com/jitpack/jitpack.io/issues/5122

**Comment by xibr** [comment]
I did a rebuild, it should work now.

**Comment by SuperSonicHub1** [comment]
Thanks!

**Comment by HaXxanParhar** [comment]
Thank you @xibr but it is still not working for me. I've tried the following dependencies but none worked (got imported).
![image](https://user-images.githubusercontent.com/38008190/174524654-444d993e-59f0-4221-9463-52e99bb0be68.png)

For the record, this is my gradle setting file:
![image](https://user-images.githubusercontent.com/38008190/174525277-9318d308-b8b5-412a-9722-869589ad7d86.png)

**Comment by SuperSonicHub1** [comment]
@HaXxanParhar I've had success with `implementation 'com.github.yausername.youtubedl-android:library:a41cfdfc69@aar'`.

**Comment by xibr** [comment]
This should work, I'll take a look when I have free time.

Use the last commit, the current last commit is `a41cfdfc69`
```
implementation 'com.github.yausername.youtubedl-android:library:a41cfdfc69'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:a41cfdfc69'
```

**Comment by HaXxanParhar** [comment]
Thank you @xibr. The above dependency is working for me. Is it okay If I close the issue when the main dependency is up and running? Because I want to get notified and update my Gradle when the main dependency is working.

**Comment by xibr** [comment]
Well, The last version should work, please can you confirm? @HaXxanParhar @SuperSonicHub1

**Comment by HaXxanParhar** [comment]
@xibr This last commit is working fine for me. Thank you.
`implementation 'com.github.yausername.youtubedl-android:library:a41cfdfc69'`

The following is not working for me. I'm closing the issue hoping this will get resolved too.
`implementation 'com.github.yausername.youtubedl-android:library:0.13.1'`

**Comment by xibr** [comment]
I mean the latest version 0.13.2 not 0.13.1
```
implementation 'com.github.yausername.youtubedl-android:library:0.13.2'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.13.2'
```

**Comment by SuperSonicHub1** [comment]
@xibr Works for me.

**Comment by HaXxanParhar** [comment]
@xibr Working for me too.
